name: holool_ecommerce
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.5
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_spinkit: ^5.2.1
  settings_ui: ^2.0.2
  shimmer: ^3.0.0
  flutter_localization: ^0.3.1
  google_nav_bar: ^5.0.6
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.9.0
  animations: ^2.0.11
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  flutter_phoenix: ^1.1.1
  flutter_animate: ^4.5.0
  delightful_toast: ^1.1.0
  flutter_cache_manager: ^3.4.1
  animated_text_kit: ^4.2.2
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.9
  http: ^1.3.0
  bloc: ^9.0.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
